## DATASET-1 (2008-2019)

In [ ]:
from zipfile import ZipFile

with ZipFile('2008-2019.zip', 'r') as zip_ref:
    zip_ref.extractall('ipl_dataset-1')

In [ ]:
import os

os.listdir("ipl_dataset-1")

['matches.csv', 'deliveries.csv']

In [ ]:
#loading the files in dataset-1
import pandas as pd

matches_df = pd.read_csv("ipl_dataset-1/matches.csv")
deliveries_df = pd.read_csv("ipl_dataset-1/deliveries.csv")

print("Both datasets loaded successfully!")

Both datasets loaded successfully!

In [ ]:
#size of the files in dataset-1
print("Matches dataset shape:", matches_df.shape)
print("Deliveries dataset shape:", deliveries_df.shape)

Matches dataset shape: (756, 18)
Deliveries dataset shape: (179078, 21)

In [ ]:
#First five rows of each file in dataset-1
print("Matches dataset:")
display(matches_df.head())

print("\nDeliveries dataset:")
display(deliveries_df.head())

Matches dataset:

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

Deliveries dataset:

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [ ]:
#seasons covered in dataset-1
print("Seasons in Dataset 1:")
print(matches_df["Season"].unique())

Seasons in Dataset 1:
['IPL-2017' 'IPL-2008' 'IPL-2009' 'IPL-2010' 'IPL-2011' 'IPL-2012'
 'IPL-2013' 'IPL-2014' 'IPL-2015' 'IPL-2016' 'IPL-2018' 'IPL-2019']

In [ ]:
#columns present in matches and deliveries csv files in dataset-1
print("Matches columns:")
print(matches_df.columns.tolist())

print("\nDeliveries columns:")
print(deliveries_df.columns.tolist())

Matches columns:
['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2', 'umpire3']

Deliveries columns:
['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs', 'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs', 'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed', 'dismissal_kind', 'fielder']

In [ ]:
#checking datatypes
print("Matches dataset data types:")
print(matches_df.dtypes)

print("\nDeliveries dataset data types:")
print(deliveries_df.dtypes)

Matches dataset data types:
id                  int64
Season             object
city               object
date               object
team1              object
team2              object
toss_winner        object
toss_decision      object
result             object
dl_applied          int64
winner             object
win_by_runs         int64
win_by_wickets      int64
player_of_match    object
venue              object
umpire1            object
umpire2            object
umpire3            object
dtype: object

Deliveries dataset data types:
match_id             int64
inning               int64
batting_team        object
bowling_team        object
over                 int64
ball                 int64
batsman             object
non_striker         object
bowler              object
is_super_over        int64
wide_runs            int64
bye_runs             int64
legbye_runs          int64
noball_runs          int64
penalty_runs         int64
batsman_runs         int64
extra_runs           int64
total_runs           int64
player_dismissed    object
dismissal_kind      object
fielder             object
dtype: object

observed that date is not in proper form (stored as text) and will be changed later

In [ ]:
#Check the unique values of important categorical columns
print("Toss decisions:")
print(matches_df["toss_decision"].unique())

print("\nMatch results:")
print(matches_df["result"].unique())

print("\nDismissal types:")
print(deliveries_df["dismissal_kind"].dropna().unique())

Toss decisions:
['field' 'bat']

Match results:
['normal' 'tie' 'no result']

Dismissal types:
['caught' 'bowled' 'run out' 'lbw' 'caught and bowled' 'stumped'
 'retired hurt' 'hit wicket' 'obstructing the field']

Dataset-1 (2008-2019) is checked, analysed & intial cleaning is done.

## DATASET-2 (2008-2026)

In [ ]:
import zipfile

with zipfile.ZipFile("2008-26.zip", "r") as zip_ref:
    zip_ref.extractall("ipl_dataset_2")

print("Dataset 2 extracted successfully!")

Dataset 2 extracted successfully!

In [ ]:
import os

print(os.listdir("ipl_dataset_2"))

['ipl_deliveries_clean.csv', 'ipl_matches_clean.csv']

In [ ]:
import glob

csv_files = glob.glob("ipl_dataset_2/*.csv")

print("CSV files found:")
print(csv_files)

CSV files found:
['ipl_dataset_2/ipl_deliveries_clean.csv', 'ipl_dataset_2/ipl_matches_clean.csv']

In [ ]:
#loading files in dataset using glob
import pandas as pd

deliveries_df2 = pd.read_csv(csv_files[0])
matches_df2 = pd.read_csv(csv_files[1])

print("Dataset 2 files loaded successfully!")
print("Deliveries shape:", deliveries_df2.shape)
print("Matches shape:", matches_df2.shape)

Dataset 2 files loaded successfully!
Deliveries shape: (295732, 14)
Matches shape: (1243, 13)

In [ ]:
print("Matches columns:")
print(matches_df2.columns.tolist())

print("\\nDeliveries columns:")
print(deliveries_df2.columns.tolist())

print("\\nSeasons available:")
print(sorted(matches_df2["season"].unique(), key=str))

Matches columns:
['match_id', 'date', 'season', 'venue', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result_type', 'result_margin', 'player_of_match']
\nDeliveries columns:
['match_id', 'innings', 'batting_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'runs_batter', 'runs_extras', 'runs_total', 'wicket', 'wicket_player_out', 'wicket_kind']
\nSeasons available:
[np.int64(2007), np.int64(2009), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

some names in columns are different

In [ ]:
#checking datatypes
print("Matches dataset data types:")
print(matches_df2.dtypes)

print("\nDeliveries dataset data types:")
print(deliveries_df2.dtypes)

Matches dataset data types:
match_id             int64
date                object
season               int64
venue               object
city                object
team1               object
team2               object
toss_winner         object
toss_decision       object
winner              object
result_type         object
result_margin      float64
player_of_match     object
dtype: object

Deliveries dataset data types:
match_id              int64
innings               int64
batting_team         object
over                  int64
ball                  int64
batter               object
bowler               object
non_striker          object
runs_batter           int64
runs_extras           int64
runs_total            int64
wicket                int64
wicket_player_out    object
wicket_kind          object
dtype: object