In [ ]:
import pandas as pd

In [ ]:
matches = pd.read_csv("/content/combined_matches_cleaned.csv")
deliveries = pd.read_csv("/content/combined_deliveries_cleaned.csv")
print("Matches:", matches.shape)
print("Deliveries:", deliveries.shape)

Matches: (1243, 12)
Deliveries: (295729, 14)

In [ ]:
display(matches.head())
display(deliveries.head())

,match_id,season,date,city,venue,team1,team2,toss_winner,toss_decision,winner,result_type,player_of_match
0,1,2017,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Sunrisers Hyderabad,normal,Yuvraj Singh
1,2,2017,2017-04-06,Pune,Maharashtra Cricket Association Stadium,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,normal,SPD Smith
2,3,2017,2017-04-07,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,normal,CA Lynn
3,4,2017,2017-04-08,Indore,Holkar Cricket Stadium,Rising Pune Supergiants,Punjab Kings,Punjab Kings,field,Punjab Kings,normal,GJ Maxwell
4,5,2017,2017-04-08,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Delhi Capitals,Royal Challengers Bengaluru,bat,Royal Challengers Bengaluru,normal,KM Jadhav

,match_id,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,wicket_player_out,wicket_kind,wicket
0,1,1,Sunrisers Hyderabad,1,1,DA Warner,TS Mills,S Dhawan,0,0,0,NaN,NaN,0
1,1,1,Sunrisers Hyderabad,1,2,DA Warner,TS Mills,S Dhawan,0,0,0,NaN,NaN,0
2,1,1,Sunrisers Hyderabad,1,3,DA Warner,TS Mills,S Dhawan,4,0,4,NaN,NaN,0
3,1,1,Sunrisers Hyderabad,1,4,DA Warner,TS Mills,S Dhawan,0,0,0,NaN,NaN,0
4,1,1,Sunrisers Hyderabad,1,5,DA Warner,TS Mills,S Dhawan,0,2,2,NaN,NaN,0

In [ ]:
#Batting aggregation
batting = deliveries.groupby("batter").agg(
    Total_Runs=("runs_batter", "sum"),
    Matches=("match_id", "nunique")).reset_index()
batting = batting.sort_values("Total_Runs", ascending=False)
display(batting.head(10))

             batter  Total_Runs  Matches
722         V Kohli        9363      275
547       RG Sharma        7347      275
585        S Dhawan        6821      221
164       DA Warner        6602      184
320        KL Rahul        5864      149
625        SK Raina        5575      200
423        MS Dhoni        5484      241
54        AM Rahane        5391      197
655       SV Samson        5207      185
34   AB de Villiers        5201      170

In [ ]:
#Bowling aggreagation
bowling = deliveries.groupby("bowler").agg(
    Total_Runs=("runs_total", "sum"),
    Matches=("match_id", "nunique"),
    Wickets=("wicket", "sum")
).reset_index()
bowling = bowling.sort_values("Wickets", ascending=False)
display(bowling.head(10))

          bowler  Total_Runs  Matches  Wickets
78       B Kumar        6076      206      243
594    YS Chahal        5549      184      242
504    SP Narine        5407      200      229
134     DJ Bravo        4480      158      207
222    JJ Bumrah        4630      158      206
405     R Ashwin        5749      217      205
393    PP Chawla        5193      191      200
425    RA Jadeja        5546      237      189
496   SL Malinga        3511      122      188
452  Rashid Khan        4417      153      187

In [ ]:
#Team aggregation
team1 = matches[
    ["match_id", "team1", "winner"]
].rename(columns={"team1": "Team"})
team2 = matches[
    ["match_id", "team2", "winner"]
].rename(columns={"team2": "Team"})
team_data = pd.concat(
    [team1, team2],
    ignore_index=True)
team_data["Win"] = (
    team_data["Team"] == team_data["winner"]
).astype(int)
team_performance = team_data.groupby("Team").agg(
    Matches=("match_id", "nunique"),
    Wins=("Win", "sum")
).reset_index()
team_performance["Win_Percentage"] = (team_performance["Wins"] /team_performance["Matches"] * 100)
display(team_performance.sort_values("Win_Percentage", ascending=False))

                           Team  Matches  Wins  Win_Percentage
4                Gujarat Titans       77    47       61.038961
0           Chennai Super Kings      266   148       55.639098
8                Mumbai Indians      291   157       53.951890
6         Kolkata Knight Riders      278   140       50.359712
13  Royal Challengers Bengaluru      286   144       50.349650
12      Rising Pune Supergiants       30    15       50.000000
11             Rajasthan Royals      251   125       49.800797
14          Sunrisers Hyderabad      211   103       48.815166
7          Lucknow Super Giants       72    34       47.222222
10                 Punjab Kings      278   128       46.043165
2                Delhi Capitals      281   126       44.839858
3                 Gujarat Lions       30    13       43.333333
5          Kochi Tuskers Kerala       14     6       42.857143
1               Deccan Chargers       75    29       38.666667
9                 Pune Warriors       46    12       26.086957

In [ ]:
#season wise aggregation
season_performance = matches.groupby("season").agg(
    Total_Matches=("match_id", "nunique")).reset_index()
display(season_performance)

    season  Total_Matches
0     2008             58
1     2009             57
2     2010             60
3     2011             73
4     2012             74
5     2013             76
6     2014             60
7     2015             59
8     2016             60
9     2017             59
10    2018             60
11    2019             60
12    2020             60
13    2021             60
14    2022             74
15    2023             74
16    2024             71
17    2025             74
18    2026             74

In [ ]:
from pathlib import Path
output = Path("outputs")
output.mkdir(exist_ok=True)
batting.to_csv(output / "batting_summary.csv",index=False)
bowling.to_csv(output / "bowling_summary.csv",index=False)
team_performance.to_csv(output / "team_summary.csv",index=False)
season_performance.to_csv(output / "season_summary.csv",index=False)
print("Stage 5 completed successfully!")

Stage 5 completed successfully!

In [ ]:
from google.colab import files
files.download("outputs/batting_summary.csv")
files.download("outputs/bowling_summary.csv")
files.download("outputs/team_summary.csv")
files.download("outputs/season_summary.csv")