In [ ]:
import pandas as pd

In [ ]:
matches = pd.read_csv("/content/combined_matches_cleaned.csv")
deliveries = pd.read_csv("/content/combined_deliveries_cleaned.csv")
print("Datasets loaded successfully!")

Datasets loaded successfully!

In [ ]:
top_scorers = deliveries.groupby("batter")["runs_batter"].sum()
top_scorers = top_scorers.sort_values(ascending=False).head(10)
display(top_scorers.reset_index())

           batter  runs_batter
0         V Kohli         9363
1       RG Sharma         7347
2        S Dhawan         6821
3       DA Warner         6602
4        KL Rahul         5864
5        SK Raina         5575
6        MS Dhoni         5484
7       AM Rahane         5391
8       SV Samson         5207
9  AB de Villiers         5201

In [ ]:
top_wickets = deliveries.groupby("bowler")["wicket"].sum()
top_wickets = top_wickets.sort_values(ascending=False).head(10)
display(top_wickets.reset_index())

        bowler  wicket
0      B Kumar     243
1    YS Chahal     242
2    SP Narine     229
3     DJ Bravo     207
4    JJ Bumrah     206
5     R Ashwin     205
6    PP Chawla     200
7    RA Jadeja     189
8   SL Malinga     188
9  Rashid Khan     187

In [ ]:
teams = pd.concat([
    matches["team1"],
    matches["team2"]
]).dropna().unique()
team_analysis = pd.DataFrame({"Team": teams})
team_analysis["Matches"] = team_analysis["Team"].apply(
    lambda t: ((matches["team1"] == t) | (matches["team2"] == t)).sum())
team_analysis["Wins"] = team_analysis["Team"].apply(lambda t: (matches["winner"] == t).sum())
team_analysis["Win_Percentage"] = (team_analysis["Wins"] /team_analysis["Matches"] * 100).round(2)
display(team_analysis.sort_values("Win_Percentage", ascending=False))

                           Team  Matches  Wins  Win_Percentage
13               Gujarat Titans       77    47           61.04
8           Chennai Super Kings      266   148           55.64
1                Mumbai Indians      291   157           53.95
5         Kolkata Knight Riders      278   140           50.36
4   Royal Challengers Bengaluru      286   144           50.35
3       Rising Pune Supergiants       30    15           50.00
9              Rajasthan Royals      251   125           49.80
0           Sunrisers Hyderabad      211   103           48.82
14         Lucknow Super Giants       72    34           47.22
7                  Punjab Kings      278   128           46.04
6                Delhi Capitals      281   126           44.84
2                 Gujarat Lions       30    13           43.33
11         Kochi Tuskers Kerala       14     6           42.86
10              Deccan Chargers       75    29           38.67
12                Pune Warriors       46    12           26.09

In [ ]:
season_analysis = matches.groupby("season")["match_id"].nunique().reset_index()
season_analysis.columns = ["Season", "Matches"]
display(season_analysis)

    Season  Matches
0     2008       58
1     2009       57
2     2010       60
3     2011       73
4     2012       74
5     2013       76
6     2014       60
7     2015       59
8     2016       60
9     2017       59
10    2018       60
11    2019       60
12    2020       60
13    2021       60
14    2022       74
15    2023       74
16    2024       71
17    2025       74
18    2026       74

In [ ]:
player_runs = deliveries.groupby("batter")["runs_batter"].sum()
player_outs = deliveries[
    deliveries["wicket"] == 1
].groupby("batter").size()
batting_average = pd.DataFrame({
    "Total_Runs": player_runs,
    "Outs": player_outs}).fillna(0)
batting_average["Batting_Average"] = (
    batting_average["Total_Runs"] /
    batting_average["Outs"].replace(0, pd.NA))
display(batting_average.sort_values("Batting_Average", ascending=False).head(10))

                 Total_Runs   Outs Batting_Average
batter
Iqbal Abdulla            88    1.0            88.0
Vivrant Sharma           69    1.0            69.0
J Bairstow              464    8.0            58.0
MN van Wyk              167    3.0       55.666667
TK Curran               104    2.0            52.0
PD Collingwood          203    4.0           50.75
B Sai Sudharsan        2515   51.0       49.313725
KL Rahul               5864  129.0       45.457364
PR Veer                  90    2.0            45.0
V Suryavanshi          1028   23.0       44.695652

In [ ]:
toss_wins = ( matches["toss_winner"] == matches["winner"]).sum()
total_matches = matches.dropna(subset=["toss_winner", "winner"]).shape[0]
toss_percentage = round(toss_wins / total_matches * 100, 2)
print("Matches with toss and winner data:", total_matches)
print("Toss winner also won:", toss_wins)
print("Percentage:", toss_percentage, "%")

Matches with toss and winner data: 1227
Toss winner also won: 633
Percentage: 51.59 %